version: '3.4'

services:
  test-api:
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_Kestrel__Certificates__Default__Password={CERTIFICATE_PASSWORD}
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
   image: testapiserver
   volumes:
     - ~/.aspnet/https:/https:ro
   build:
      context: .
      dockerfile: Dockerfile
   ports:
      - 49154:80
      - 49155:443